account/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'account'

urlpatterns = [
    # path('', views.index, name='index'),
    url(r'sign-in/', views.LoginPage.as_view(), name='signin'),
    url(r'^password/$', views.profile, name='change_password'),
    url('sign-up', views.signup, name='signup'),
    url('dashboard', views.profile, name='profile'),
    # path('resendOTP', resend_otp),
    url('send-otp/', views.send_otp, name='send_otp')
    # url(r'^settings/$', core_views.settings, name='settings'),
    # url(r'^settings/password/$', core_views.password, name='password'),
]

home/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:slug>',views.category_page,name='category'),
    path('product/<slug:slug>',views.product_page,name='product'),
    # path('update_item/', views.updateItem, name="update_item"),
    path('ajaxsize/', views.ajaxsize, name='ajaxsize'),
    path('contact-us',views.contactus,name='contactus'),
    path('wishlist',views.wishlistPage,name='wishlistPage'),
    

    # path('order-list',views.orderlist,name='orderlist'),
    # path('invoice-details/<str:book>/', views.invoice_details_user, name='invoice_details_user'),
    # path('thankyou',views.thankyou,name='thankyou'),

]

sayra/urls.py
from django.contrib import admin

from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


from django.contrib.auth.views import LoginView, LogoutView
# from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth_views
# from django.contrib.auth import views as auth_views
from home import views as core_views



urlpatterns = [
 path('admin/', admin.site.urls),
    url(r'^filer/', include('filer.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('account.urls', namespace='account')),
    path('', include('home.urls', namespace='home')),
    path('', include('shop.urls', namespace='shop')),
    url('sign-in/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(),{'next_page': '/loginpage'}, name='logout'),
    # url('^', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# on prod
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.STATIC_URL)

shop/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'shop'

urlpatterns = [
    path('cart',views.cart,name='cart'),
    path('checkout',views.checkout,name='checkout'),

    path('wishlists/<int:id>',views.wishlists,name='wishlists'),
    path('add-to-cart',views.addtocart,name='addtocart'),
    path('delete-from-cart/<int:id>',views.deletefromcart,name='deletefromcart'),
    path('Checkout-Page-Details/', views.checkoutDetails, name='checkoutDetails'),



    path('Check-Response/', views.check_response, name='check_response'),

    # path('invoice123',views.invoice_check,name='invoice_check'),
    # path('invoice',views.invoice_check1,name='invoice_check1')


    url(r'^order-summary/$', views.orderlist, name="order_summary"),
    # url(r'^success/$', views.success, name='purchase_success'),
    # url(r'^update-transaction/(?P<token>[-\w]+)/$', views.update_transaction_records,name='update_records'),

]

home/views.py
from django.shortcuts import render, redirect
from .models import *
from account.models import *
from shop.models import *
from . utils import cookieCart, cartData, guestOrder

from django.contrib.auth.decorators import login_required, user_passes_test

import os



import json
# Create your views here.
from django.db.models import F
from django.db.models import Q

from django.contrib.auth.forms import UserCreationForm

from django.shortcuts import  get_object_or_404
from django.urls import reverse
#Paging
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.decorators.csrf import csrf_exempt
import requests
import hashlib
import hmac
import base64
# import reportlab
import string
from hashlib import sha256
from django.db.models import Count

from rest_framework import pagination


from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse


from django.urls import reverse_lazy
from django.views import generic

import math
from django.core.mail import send_mail
from django.contrib.auth.models import User, Group


# import souvenir.settings as sett,BASE_DIR
# from .paytm import generate_checksum, verify_checksum

import json

from datetime import date
import random


import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
# from django.db.models.signals import m2m_changed



from django.utils.text import slugify
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from django.contrib.auth import authenticate, user_logged_in
from django.core.mail import send_mail as sm
from django.conf import settings

#html email required
from django.core.mail  import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.exceptions import ObjectDoesNotExist

from django.db.models.signals import m2m_changed
def toppings_changed(sender, instance,action,**kwargs):
    # print(action)
    if action == 'post_add':
        print("-------- in generate meta")
        instance.meta = instance.ProductName.replace(',',' ')
        for items in instance.SubcatName.all():
            instance.meta += ' ' + items.name+' '
            instance.save()

        for items in instance.CategoryName.all():
            instance.meta += ' ' +items.CategoryName
            instance.save()

        print('slug==================',instance.meta)
        # instance.title_name.first().book_name + " " + instance.title_name.first().book_publisher.first().publisher_name + " " + instance.title_class.first().class_name

        instance.slug = instance.ProductName.replace(' ','-').lower().replace("'",'').replace('.','').replace('(','-').replace(')','-').replace('/','-').replace(',','-')
        # for items in instance.SubcatName.all():
        #     instance.slug += '-' + items.name.replace(' ','-').lower().replace("'",'').replace('.','').replace('(','-').replace(')','-').replace('/','-').replace(',','-')
        #     # print('instance.slug==',instance.slug)
        # for items in instance.CategoryName.all():
        #     instance.slug += '-' +items.CategoryName.replace(' ','-').lower().replace("'",'').replace('.','').replace('(','-').replace(')','-').replace('/','-').replace(',','-')
            # print('instance.slug==================',instance.slug)
        instance.slug = instance.slug.replace('--','-')
         # instance.title_name.first().book_publisher.first().publisher_name.replace(' ','-').lower() + "-" + instance.title_class.first().class_name.replace(' ','-').lower()
        instance.save()
    elif action == 'post_remove':
        print("-------- in generate meta")
        instance.meta = instance.ProductName.replace(',',' ')
        for items in instance.SubcatName.all():
            instance.meta += ' ' + items.name+' '
            instance.save()

        for items in instance.CategoryName.all():
            instance.meta += ' ' +items.CategoryName
            instance.save()

        print('slug==================',instance.meta)
        # instance.title_name.first().book_name + " " + instance.title_name.first().book_publisher.first().publisher_name + " " + instance.title_class.first().class_name

        instance.slug = instance.ProductName.replace(' ','-').lower().replace("'",'').replace('.','').replace('(','-').replace(')','-').replace('/','-').replace(',','-')
        # for items in instance.SubcatName.all():
        #     instance.slug += '-' + items.name.replace(' ','-').lower().replace("'",'').replace('.','').replace('(','-').replace(')','-').replace('/','-').replace(',','-')
        #     # print('instance.slug==',instance.slug)
        # for items in instance.CategoryName.all():
        #     instance.slug += '-' +items.CategoryName.replace(' ','-').lower().replace("'",'').replace('.','').replace('(','-').replace(')','-').replace('/','-').replace(',','-')
            # print('instance.slug==================',instance.slug)
        instance.slug = instance.slug.replace('--','-')
         # instance.title_name.first().book_publisher.first().publisher_name.replace(' ','-').lower() + "-" + instance.title_class.first().class_name.replace(' ','-').lower()
        instance.save()
        # print("nooooooooooo")
    else:
        pass
# m2m_changed.connect(toppings_changed, sender=titleMaster.title_class.through)
m2m_changed.connect(toppings_changed, sender=product.SubcatName.through)




def generate_order_id():
    date_str = "SAY"+date.today().strftime('%Y%m%d')[2:] + str(datetime.datetime.now().second)
    # print(date_str)
    rand_str = "".join([random.choice(string.digits) for count in range(3)])
    # print(rand_str)
    return date_str + rand_str


def getList(dict):
    return dict.keys()


# def hello(request):
#     print("yes")
#
#     return response

@receiver(user_logged_in)
def adding_cart(sender, user, request, **kwargs):
    try:
        device = request.COOKIES['device']
        try:
            order = Order.objects.get(device=device,complete=False)
        except:
            order = Order.objects.get(profile=request.user.profile.first(),complete=False)
        if not order.device:
            order.device = device
        if not order.order_num:
            order.order_num = generate_order_id()
        order.save()
    except:
        try:
            device = request.COOKIES['device']

            if request.user.is_authenticated:
                order = Order.objects.create(profile=request.user.profile.first(),device=device,complete=False)
                if not order.order_num:
                    order.order_num = generate_order_id()
            else:
                order = Order.objects.create(device=device,complete=False)
                if not order.order_num:
                    order.order_num = generate_order_id()
            order.save()
        except :
            pass


    try:
        anonyOrder = Order.objects.get(device = device, complete=False)
        logedOrder = Order.objects.get(profile = request.user.profile.first(), complete=False)
        anony = OrderItem.objects.filter(order = anonyOrder)
        loged = OrderItem.objects.filter(order = logedOrder)

        for i in anony:
            for j in loged:
                if i.product == j.product:
                    if i.variant == j.variant:
                        j.quantity += i.quantity
                        logedOrder.device = device
                        j.save()
                        logedOrder.save()
                        i.delete()
                        anonyOrder.delete()
                else:
                    j.quantity += i.quantity
                    logedOrder.device = device
                    i.delete()
                    anonyOrder.delete()
                    j.save()
                    logedOrder.save()
    except:
        pass


def index(request):
    profile = None
    order = None
    wish = []
    if request.user.is_authenticated:
        profile = request.user.profile
        wishing = Wishlist.objects.filter(user=profile)
        for item in wishing:
            wish.append(item.wished_item.id)
        try:
            order = Order.objects.get(profile=profile, complete=False)
        except ObjectDoesNotExist:
            order = None
    first_banners = Widgets.objects.get(priority=1).banner_set.all().order_by('priority')
    second_banners = Widgets.objects.get(priority=2).banner_set.all().order_by('priority')
    category = Category.objects.all()
    feature = FeaturedItem.objects.all().order_by('-id')
    best_seller = bestseller.objects.all().order_by('-id')
    context = {'first_banners': first_banners,
               'second_banners': second_banners,
               'Category': category,
               'order': order,
               'feature': feature,
               'best_seller': best_seller,
               'wish': wish,
               'profile': profile
               }
    return render(request,'index.html',context)


def category_page(request, slug):
    profile = None
    order = None
    wish = []
    wishing = []
    if request.user.is_authenticated:
        profile = request.user.profile
        wishing = Wishlist.objects.filter(user=profile)
        for item in wishing:
            wish.append(item.wished_item.id)
        try:
            order = Order.objects.get(profile=profile, complete=False)
        except ObjectDoesNotExist:
            order = None
    category = Category.objects.all()
    Prod = product.objects.filter(CategoryName__slug=slug)

    context = {
        'Category':category,
        'wishing':wishing,
        'wish':wish,
        'Product':Prod,
        'order': order,
        'sluging':slug,
        'profile':profile
    }
    return render(request,'category.html',context)

def visitor_ip_address(request):

home/templates/category.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <main class="ps-main">
      <div class="ps-products-wrap pt-40 pb-80">
        <div class="ps-products" data-mh="product-listing">
          <div class="ps-product__columns">
            {% if Product %}
            {% for item in Product %}
            <div class="ps-product__column">
              <div class="ps-shoe mb-30">
                <div class="ps-shoe__thumbnail">
                  <!-- <div class="ps-badge"><span>New</span></div> -->
                  {% if item.discount_percent == 0 %}
                  {% else %}
                  <div class="ps-badge ps-badge--sale"><span>-{{item.discount_percent}}%</span></div>
                  {% endif %}
                  {% if user.is_authenticated %}

                  {% if item.id in wish %}

                  <a class="ps-shoe__favorite " style="color:#F4CB79;background:#F4CB79;" href="{% url 'shop:wishlists' item.id %}">
                    <i class="ps-icon-heart"></i></a>
                    {% else %}
                    <a class="ps-shoe__favorite" href="{% url 'shop:wishlists' item.id %}">
                      <i class="ps-icon-heart"></i></a>
                    {% endif %}
                      {% endif %}
                  <img src="{{ item.productimages.first.image.url }}" alt="{{item.ProductName}}">
                  <a class="ps-shoe__overlay" href="{% url 'home:product' item.slug %}"></a>
                </div>
                <div class="ps-shoe__content">
                  <div class="ps-shoe__variants">
                    <div class="ps-shoe__variant normal"><img src="{{ item.productimages.first.image.url }}" alt="{{item.ProductName}}">
                      {% for image in item.productimages.all %}
                      <img src="{{ image.image.url }}" alt="{{item.ProductName}}">
                      {% endfor %}
                     </div>

                  </div>
                  <div class="ps-shoe__detail"><a class="ps-shoe__name" href="{% url 'home:product' item.slug %}">{{item.ProductName}}</a>
                    <!-- <p class="ps-shoe__categories"><a href="#">Men shoes</a>,<a href="#"> Nike</a>,<a href="#"> Jordan</a></p> -->
                    <span class="ps-shoe__price">
                      {% if item.discount_percent == 0 %}
                      ₹{{item.price}}
                      {% else %}
                      <del>₹{{item.price}}</del> ₹{{item.discount_price}}</span>
                      {% endif %}
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}

                        <center>    <img src="{% static 'img/no_result.jpeg' %}" alt="No result Found" class="ml-auto mr-auto img img-fluid " width="50%"  > </center>
                            {% endif %}
          </div>

        </div>

      </div>


      <script type="text/javascript">





  function resetAll(){

      var newURL = location.href.split("?")[0];
      window.history.pushState('object', document.title, newURL);
      window.location.reload()
      $(':checkbox').prop('checked', false);
  }



</script>
    </main>
      {% endblock %}

home/templates/color.html
  <input type="hidden" id="productId" name="productId" value="{{productid}}">
  <input type="hidden" id="variantId" name="variantId" value="{{variant.id}}">
  <input type="hidden" id="size" name="size" value="{{size}}">

<select class="" style="display: inline-block !important;" onchange="this.form.submit();">
  <option value="1">Select Color</option>
  {% for item in variantscol %}
  <option value="{{item.color.id}}">{{item.color}}</option>
  {% endfor %}
  </select>

home/templates/footer.html
{% load static %}

<div class="ps-footer bg--cover" data-background="" style="padding: 10px 20px;">
  <div class="ps-footer__content" style="margin-bottom: -40px;">
    <div class="ps-container">
      <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 ">
              <aside class="ps-widget--footer ps-widget--info">
                <header>

                  <a class="ps-logo" href="{% url 'home:index' %}" style="margin-bottom:0px">
                  <img src="{% static 'img/3.png' %}" alt=""></a>

                  <h3 class="ps-widget__title">Sayra Apparels Pvt Ltd</h3>
                </header>
                <footer>
                  <p><strong>Village - salempur Gosain,  Gajraula, Amroha, Uttar Pradesh - 244235</strong></p>
                  <p>Email: <a href='mailto:support@sayra.in'>support@sayra.in</a></p>
                  <p>Phone: +91-9927300827</p>
                  <!-- <p>Fax: ++323 32434 5333</p> -->
                </footer>
              </aside>
            </div>
            <!--<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 ">-->
            <!--  <aside class="ps-widget--footer ps-widget--info second">-->
            <!--    <header>-->
            <!--      <h3 class="ps-widget__title">Address Office 2</h3>-->
            <!--    </header>-->
            <!--    <footer>-->
            <!--      <p><strong>PO Box 16122 Collins  Victoria 3000 Australia</strong></p>-->
            <!--      <p>Email: <a href='mailto:support@store.com'>support@store.com</a></p>-->
            <!--      <p>Phone: +323 32434 5334</p>-->
            <!--      <p>Fax: ++323 32434 5333</p>-->
            <!--    </footer>-->
            <!--  </aside>-->
            <!--</div>-->
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 ">
              <aside class="ps-widget--footer ps-widget--link">
                <header>
                  <h3 class="ps-widget__title">Find Our store</h3>
                </header>
                <footer>
                  <ul class="ps-list--link">
                    <li><a href="#">About Sayra</a></li>
                    <li><a href="#">Purchase Flow</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="{% url 'home:contactus' %}">Contact Us</a></li>
                  </ul>
                </footer>
              </aside>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 ">
              <aside class="ps-widget--footer ps-widget--link">
                <header>
                  <h3 class="ps-widget__title">Customer Help</h3>
                </header>
                <footer>
                  <ul class="ps-list--line">
                    <li><a target="blank" href="{% static 'pdf/companyinfo.pdf' %}">Terms & Condition</a></li>
                    <li><a target="blank" href="{% static 'pdf/privacypolicy.pdf' %}">Privacy Policy</a></li>
                    <li><a target="blank" href="{% static 'pdf/refundpolicy.pdf' %}">Refund Policy</a></li>
                    <li><a target="blank" href="{% static 'pdf/return&exchange.pdf' %}">Disclaimer</a></li>
                    <li><a target="blank" href="{% static 'pdf/shippingpolicy.pdf' %}">Shipping Policy</a></li>
                    <!-- <li><a target="blank" href="{% static 'pdf/terms&condition.pdf' %}">Terms & Exchange</a></li> -->

                  </ul>
                </footer>
              </aside>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 ">
              <aside class="ps-widget--footer ps-widget--link">
                <header>
                  <h3 class="ps-widget__title">My Account</h3>
                </header>
                <footer>
                  <ul class="ps-list--line">
                    <li><a href="{% url 'shop:cart' %}">View Cart</a></li>
                    <li><a href="#">Track My Order</a></li>
                    <li><a href="{% url 'home:contactus' %}">Help</a></li>
                    <!-- <li><a href="#">Football Boots</a></li> -->
                  </ul>
                </footer>
              </aside>
            </div>
      </div>
    </div>
  </div>
  <div class="ps-footer__copyright">
    <div class="ps-container">
      <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
              <p>&copy; <a href=""> Sayra</a>, Inc. All rights Resevered. Design by <a href="https://digisahay.com" target="_blank">DigiSahay LLP</a></p>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
              <ul class="ps-social">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              </ul>
            </div>
      </div>
    </div>
  </div>
</div>
</main>

home/templates/nav.html
{% load static %}
{% load home_tags %}
<header class="header">
  <nav class="navigation" style="border-bottom: 1px solid #eee;">
    <div class="container-fluid">
      <div class="navigation__column left">
        <div class="header__logo"><a class="ps-logo" href="{% url 'home:index' %}">
          <img src="{% static 'img/3.png' %}" alt=""></a></div>
      </div>
      <div class="navigation__column center">
            <ul class="main-menu menu">
              <!-- <li class="menu-item menu-item-has-children dropdown"><a href="{% url 'home:index' %}">Home</a>

              </li> -->
              {% for item in Category %}
              {% if forloop.counter <= 4 %}

              <li class="menu-item"><a  href="{% url 'home:category' item.slug %}">{{item.Name}}</a>
              </li>
              {% endif %}
              {% endfor %}
{% comment %}
{% if item.parent.exists %}
{% endif %}
                <!-- <div class="mega-menu">
                  <div class="mega-wrap">
                    {% for items in category1 %}
                    {% if item.id == items.parent.id %}
                    <div class="mega-column">
                    {% if items.SubcatName.all %}

                      <h4 class="mega-heading">{{items}}</h4>

                      <ul class="mega-item">
                        {% for i in items.SubcatName.all %}
                        <li><a href="/category?Sub_category={{i}}">{{i}}</a></li>

                        {% endfor %}

                      </ul>
                      {% endif %}
                    </div>

                    {% endif %}
                    {% endfor %}
                  </div>
                </div> -->
{% endcomment %}




              <!-- <li class="menu-item"><a href="">All Categories</a></li> -->
              <li class="menu-item menu-item-has-children dropdown"><a href="">Info</a>
                    <ul class="sub-menu">
                      <li class="menu-item"><a href="{% url 'home:contactus' %}">Contact Us</a>

                      <li class="menu-item"><a href="">About Us</a></li>
                      <li class="menu-item"><a href="">FAQs</a></li>
                      </ul>
                      </li>

              <!-- <li class="menu-item menu-item-has-children dropdown"><a href="{% url 'home:contactus' %}">Contact</a>

              </li> -->
            </ul>
      </div>
      <div class="navigation__column right">
        {% comment %}
        {% for item in Category %}
        {% if item.active %}
        <form class="ps-search--header" action="{% url 'home:category' item.slug %}" method="get">
            {% else %}
            <form class="ps-search--header" action="{% url 'home:contactus' %}" method="get">

              {% endif %}
              {% endfor %}

          <input class="form-control" type="text" name ="q" placeholder="Search Product…">
          <button><i class="ps-icon-search"></i></button>
        </form>
        {% endcomment %}
          <div class="ps-cart">
             {% if request.user.is_authenticated %}
                <div class="btn-group ps-dropdown">
                  <a class="dropdown-toggle  ps-cart__toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   {% with profile.name|get_initials as initial %}
                    <i>{{ initial }}</i>
                    {% endwith %}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'account:profile' %}">Profile</a></li>
                    <li><a href="{% url 'home:wishlistPage' %}">Wishlist</a></li>
                    <li><a href="{% url 'shop:order_summary' %}">Your Orders</a></li>
                    <li><a href="/logout">Logout</a></li>
                  </ul>
                </div>
                {% else %}
                <a class="ps-cart__toggle" href="{% url 'account:signin' %}">
                  <i><img src="{% static 'images/login_image.png' %}"></i>

                </a>
                {% endif %}
          </div>
        <div class="ps-cart">
          <a class="ps-cart__toggle"  href="{% url 'home:wishlistPage' %}">
                <i class="ps-icon-heart"></i></a>
        </div>
        <div class="ps-cart"><a class="ps-cart__toggle" href="#"><span><i>{% if order.get_cart_items %}{{ order.get_cart_items }} {% else %} 0 {% endif %}</i></span><i class="ps-icon-shopping-cart"></i></a>
          <div class="ps-cart__listing">
            {% if order.get_cart_items %}
            <div class="ps-cart__content">
              {% for item in order.OrderItem.all %}
              <div class="ps-cart-item"><a class="ps-cart-item__close" href="{% url 'shop:deletefromcart' item.id %}"></a>
                <div class="ps-cart-item__thumbnail"><a href=""></a>
                  {% if item.variant %}

                  <img src="{{ item.variant.image_id.image1.url }}" alt="{{ item.variant.title }}">
                  {% else %}
                  <img src="{{ item.product.productimages.first.image1.url }}" alt="{{ item.product.ProductName }}">

                  {% endif %}

                </div>
                <div class="ps-cart-item__content"><a class="ps-cart-item__title" href="">
                  {% if item.variant %}
                  {{ item.variant.title }}
                  {% else %}
                  {{ item.product.ProductName }}

                  {% endif %}
                </a>

                  <p><span>Quantity:<i>{{ item.quantity }}</i></span>
                    {% if item.variant %}
                    <span>Total:<i>₹ {{ item.get_vari_total }}</i></span>
                    {% else %}
                    <span>Total:<i>₹ {{ item.get_prod_total }}</i></span>

                    {% endif %}

                  </p>
                </div>
              </div>
              {% endfor %}

            </div>
            <div class="ps-cart__total">
              <p>Number of items:<span>{{ order.get_cart_items }}</span></p>
              {% if order.get_ship_total == 0 %}
              <p>Shipping Charges:<span>FREE</span></p>

              {% else %}
              <p>Shipping Charges:<span>{{ order.get_ship_total }}</span></p>

              {% endif %}
              <p>Item Total:<span>₹ {{ order.get_cart_ship_total }}</span></p>
            </div>
            <div class="ps-cart__footer"><a class="ps-btn" style="width:40%;" href="{% url 'shop:cart' %}">Cart<i class="ps-icon-shopping-cart"></i></a>
              <a class="ps-btn" style="width:60%;" href="{% url 'shop:checkout' %}">Checkout<i class="ps-icon-arrow-left "></i></a></div>
            {% else %}
            <div class="ps-cart__footer"><a class="ps-btn" href="{% url 'home:index' %}">Shop Now<i class="ps-icon-shopping-cart"></i></a></div>

            {% endif %}
          </div>

        </div>
        <div class="menu-toggle"><span></span></div>
      </div>
    </div>
  </nav>

</header>

home/templates/wishlist.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="ps-content pt-80 pb-80">
  <div class="ps-container">
    <div class="ps-cart-listing ps-table--whishlist">
      {% if wish %}
      <table class="table ps-cart__table">
        <thead>
          <tr>
            <th>All Products</th>
            <th>Price</th>
            <th>View</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for item in wish %}
          <tr>
            <td style="width: max-content;" >
              <a class="ps-product__preview" href="{% url 'home:product' item.wished_item.slug %}">
                <img class="mr-15 ps-shoe__variant" style="height:150px;" src="{{ item.wished_item.productimages.first.image.url }}" alt="{{ item.wished_item.ProductName }}"> {{ item.wished_item.ProductName }}</a></td>
            <td>  {% if item.wished_item.discount_percent == 0 %}
              ₹{{item.wished_item.price}}
              {% else %}
              <del>₹{{item.wished_item.price}}</del> ₹{{item.wished_item.discount_price}}
              {% endif %}</td>
            <td><a class="ps-product-link" href="{% url 'home:product' item.wished_item.slug %}">View Product</a></td>
            <td>
              <a href="{% url 'shop:wishlists' item.wished_item.id %}"><div class="ps-remove"></div></a>
            </td>
          </tr>
          {% endfor %}
          <!-- <tr>
            <td><a class="ps-product__preview" href="product-detail.html"><img class="mr-15" src="images/product/cart-preview/2.jpg" alt=""> The Crusty Croissant</a></td>
            <td>$150</td>
            <td><a class="ps-product-link" href="product-detail.html">View Product</a></td>
            <td>
              <div class="ps-remove"></div>
            </td>
          </tr>
          <tr>
            <td><a class="ps-product__preview" href="product-detail.html"><img class="mr-15" src="images/product/cart-preview/3.jpg" alt="">The Rolling Pin</a></td>
            <td>$150</td>
            <td><a class="ps-product-link" href="product-detail.html">View Product</a></td>
            <td>
              <div class="ps-remove"></div>
            </td>
          </tr> -->
        </tbody>
      </table>
      {% else %}
      <img src="{% static 'img/wishlist.jpg' %}" alt="">
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}