home/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:slug>',views.category_page,name='category'),
    path('product/<slug:slug>',views.product_page,name='product'),
    # path('update_item/', views.updateItem, name="update_item"),
    path('ajaxsize/', views.ajaxsize, name='ajaxsize'),
    path('contact-us',views.contactus,name='contactus'),
    path('wishlist',views.wishlistPage,name='wishlistPage'),
    

    # path('order-list',views.orderlist,name='orderlist'),
    # path('invoice-details/<str:book>/', views.invoice_details_user, name='invoice_details_user'),
    # path('thankyou',views.thankyou,name='thankyou'),

]

sayra/urls.py
from django.contrib import admin

from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


from django.contrib.auth.views import LoginView, LogoutView
# from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth_views
# from django.contrib.auth import views as auth_views
from home import views as core_views



urlpatterns = [
 path('admin/', admin.site.urls),
    url(r'^filer/', include('filer.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('account.urls', namespace='account')),
    path('', include('home.urls', namespace='home')),
    path('', include('shop.urls', namespace='shop')),
    url('sign-in/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(),{'next_page': '/loginpage'}, name='logout'),
    # url('^', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# on prod
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.STATIC_URL)

shop/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'shop'

urlpatterns = [
    path('cart',views.cart,name='cart'),
    path('checkout',views.checkout,name='checkout'),

    path('wishlists/<int:id>',views.wishlists,name='wishlists'),
    path('add-to-cart',views.addtocart,name='addtocart'),
    path('delete-from-cart/<int:id>',views.deletefromcart,name='deletefromcart'),
    path('Checkout-Page-Details/', views.checkoutDetails, name='checkoutDetails'),



    path('Check-Response/', views.check_response, name='check_response'),

    # path('invoice123',views.invoice_check,name='invoice_check'),
    # path('invoice',views.invoice_check1,name='invoice_check1')


    url(r'^order-summary/$', views.orderlist, name="order_summary"),
    # url(r'^success/$', views.success, name='purchase_success'),
    # url(r'^update-transaction/(?P<token>[-\w]+)/$', views.update_transaction_records,name='update_records'),

]

shop/views.py
from django.shortcuts import render, redirect
from .models import *
from home.models import *
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import string
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
import random
import razorpay
from django.core.exceptions import ObjectDoesNotExist

keyID = 'rzp_test_tUKqhcADEgW9fB'
secretKey = 'VuhjcEHGQUuo1xJOSMHgTLqa'

client = razorpay.Client(auth=(keyID,secretKey))

def generate_order_id():
    date_str = "SAY"+date.today().strftime('%Y%m%d')[2:] + str(datetime.datetime.now().second)
    # print(date_str)
    rand_str = "".join([random.choice(string.digits) for count in range(3)])
    # print(rand_str)
    return date_str + rand_str


@login_required
def cart(request):
    try:
        order = Order.objects.get(profile=request.user.profile, complete=False)
    except ObjectDoesNotExist:
        order = None
    category = Category.objects.all()
    context = {
        'Category': category,
        'order': order,
        'profile': request.user.profile
    }
    return render(request, 'cart.html', context)


@login_required
def checkout(request):
    try:
        profile = UserProfile.objects.get(user=request.user)
    except:
        profile= None
    try:
        order = Order.objects.get(profile=profile, complete=False)
        if not order.order_num:
            order.order_num = generate_order_id()
        order.save()
    except:
        order = None
    category = Category.objects.all()
    form = invoiceModelForm()

    if request.method == "POST":

        print("===================================================================================")
        form = invoiceModelForm(request.POST or None)
        form.full_clean()
        print("invoiceform=====--======-----",form.errors)

    # check if form data is valid
        if form.is_valid():
        # save the form data to model
            invoiceForm = form.save()
            invoiceForm.order_id = order.order_num
            invoiceForm.owner = profile
            invoiceForm.save()
            # abc = invoiceModel.objects.get(id=invoiceForm.pk)
            #
            # print(abc)
            return redirect(reverse('shop:checkoutDetails'))
        else:
            messages.warning(request,'Please fill the form correctly')

    context = {
        'Category':category,
        'order':order,
        'profile':profile,
        'form':form,

    }
    return render(request,'checkout.html',context)

@login_required
def checkoutDetails(request):
    try:
        profile = UserProfile.objects.get(user=request.user)
    except:
        profile= None
    try:
        try:
            device = request.COOKIES['device']
            order = Order.objects.get(device=device,complete=False)
            if not order.device:
                order.device = device
            order.save()
        except:
            order = Order.objects.get(profile=profile,complete=False)

        if not order.order_num:
            order.order_num = generate_order_id()
        order.save()
    except:
        order = None
    category = Category.objects.all()
    subcate = subcategory.objects.all()
    # print(client)
    newOrder = Order.objects.get(profile = profile, complete=False)
    print(newOrder,profile)
    invoice = invoiceModel.objects.filter(owner = profile,order_id=newOrder,success=False).last()

    newOrder.is_initiated = True
    newOrder.save()


    order_amount = int(newOrder.get_cart_total*100),
    order_currency = 'INR'
    order_receipt = newOrder.order_num
    # notes = {'Shipping address': 'Bommanahalli, Bangalore'}   # OPTIONAL
    # print(order_amount)

    response = client.order.create(dict(amount=order_amount[0], currency=order_currency,receipt=order_receipt))
    order_id = response['id']
    order_status = response['status']

    if order_status=='created':
        context ={'price':order_amount,
                  'name': invoice.nameDetail,
                  'phone': str(invoice.phone_number),
                  'email' : invoice.email,
                  'invoice_id' : order_id,
                  'invoice':invoice,
                  # 'order_num' : newOrder
                  }
        return render(request, 'checkoutload.html', context)

    return HttpResponse('<h1>Error! Please Try again later</h1>')


from django.templatetags.static import static
#from django.contrib.staticfiles.templatetags.staticfiles import static
from fpdf import FPDF, HTMLMixin
class HTML2PDF(FPDF, HTMLMixin):
    pass

from datetime import timedelta
import datetime
from datetime import date
@login_required
@csrf_exempt
def check_response(request):
    try:
        profile = UserProfile.objects.get(user=request.user)
    except:
        profile= None
    try:
        try:
            device = request.COOKIES['device']
            order = Order.objects.get(device=device,complete=False)
            if not order.device:
                order.device = device
            order.save()
        except:
            order = Order.objects.get(profile=profile,complete=False)

        if not order.order_num:
            order.order_num = generate_order_id()
        order.save()
    except:
        order = None
    print(order)
    response = request.POST

    params_dict = {
        'razorpay_payment_id' : response.get('razorpay_payment_id'),
        'razorpay_order_id' : response.get('razorpay_order_id'),
        'razorpay_signature' : response.get('razorpay_signature')
    }
    status = client.utility.verify_payment_signature(params_dict)
    print("status======",status)
    order_items =  OrderItem.objects.filter(order=order)
    transaction = Transaction.objects.create(profile=order.profile,
                    token=params_dict['razorpay_payment_id'],
                    order_id=order.order_num,
                    amount= order.get_cart_total  ,
                    success=True)
    invoice = invoiceModel.objects.filter(order_id=order.order_num).last()
    invoice.transaction_id = Transaction.objects.get(id=transaction.pk)
    invoice.success = True

    for item in order_items:
        invoice.order_item.add(item)
        invoice.save()
    invoice.save()
    order.complete=True
    order.save()
    return render(request, 'Thankyou.html', {'status': 'Payment Successful','order':order,'amount':order.get_cart_total})






def wishlists(request,id):
    profile = UserProfile.objects.get(user=request.user)
    prod = product.objects.get(id=id)

    if Wishlist.objects.filter(wished_item=prod,user=profile).exists() :
        print("hello")
        wish = Wishlist.objects.filter(wished_item=prod,user=profile).delete()
    else:
        wish = Wishlist.objects.create(wished_item=prod,user=profile)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def addtocart(request):
    if request.method == 'POST':
        product_id = request.POST.get('productval')
        quantity = request.POST.get('quant')
        prod = product.objects.get(id=product_id)
        order, created = Order.objects.get_or_create(profile=request.user.profile, complete=False)
        if not order.order_num:
            order.order_num = generate_order_id()
        order.save()
        if OrderItem.objects.filter(order=order, product=prod).exists():
            return HttpResponse(status=404)
        OrderItem.objects.create(order=order, product=prod, quantity=quantity, tax_amount=prod.tax_amount,
                                 unit_price=prod.unit_price, discount_percentage=prod.discount_percent)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def removefromcart(request):
    if request.method == 'POST':

        device = request.COOKIES['device']
        productId = request.POST.get('productval')
        varientId = request.POST.get('varientval')
        quantity = request.POST.get('quant')

        try:
            Variant = Variants.objects.get(id=varientId)
            Product = product.objects.get(id=productId)
        except:
            Product = product.objects.get(id=productId)

        if request.user.is_authenticated:
            profile = UserProfile.objects.get(user=request.user)
            order = Order.objects.get(profile=profile,complete=False)
        else:
            order = Order.objects.get(device=device,complete=False)
        if varientId is None:
            orderItem = OrderItem.objects.get(order=order,product=Product,variant=None)
        else:
            orderItem = OrderItem.objects.get(order=order,product=Product,variant=Variant)

        orderItem.quantity-=int(quantity)
        orderItem.save()
        #     try:
        #         orderItem = OrderItem.objects.get()
        #     print("hello Add to cart")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def deletefromcart(request,id):
    orderItem = OrderItem.objects.get(id=id)

    orderItem.delete()
        # orderItem.save()
        #     try:
        #         orderItem = OrderItem.objects.get()
        #     print("hello Add to cart")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    

@login_required
def orderlist(request):
    category = Category.objects.all()
    user_order_list = Order.objects.filter(profile=request.user.profile, complete=True)

    deliver = Delivery.objects.all()
    context = {
        'Category': category,
        'new_profile': request.user.profile,

        'user_order_list': user_order_list,
        'deliver': deliver
    }
    return render(request, 'userorder.html',context)

shop/templates/Thankyou.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="{% static 'img/1.png' %}" rel="apple-touch-icon">
    <link href="{% static 'img/1.png' %}" rel="icon">
    <meta name="author" content="Sayra">
    <meta name="keywords" content="Women Collection">
    <meta name="description" content="Default keyword">
    <title>Sayra</title>
    <!-- Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Archivo+Narrow:300,400,700%7CMontserrat:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/ps-icon/style.css' %}">
    <!-- CSS Library-->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/owl-carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/jquery-bar-rating/dist/themes/fontawesome-stars.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/slick/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/Magnific-Popup/dist/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/revolution/css/settings.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/revolution/css/layers.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/revolution/css/navigation.css' %}">

    <!-- Custom-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/material-design-iconic-font.min.css' %}">
  </head>
  <!--[if IE 7]><body class="ie7 lt-ie8 lt-ie9 lt-ie10"><![endif]-->
  <!--[if IE 8]><body class="ie8 lt-ie9 lt-ie10"><![endif]-->
  <!--[if IE 9]><body class="ie9 lt-ie10"><![endif]-->
  <body class="ps-loading">
    <div class="ps-404 bg--cover" data-background="images/background/404.jpg">
      <div class="ps-404__content">
        <!-- <h1>404</h1>
        <h3>Page not found</h3>
        <p>The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.</p> -->

        <a class="ps-btn" href="{% url 'home:index' %}">Back to home<i class="ps-icon-next"></i></a>
      </div>
    </div>
    <main class="ps-main">
    </main>
    <!-- JS Library-->
    <<script type="text/javascript" src="{% static 'plugins/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/jquery-bar-rating/dist/jquery.barrating.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/owl-carousel/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/gmap3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/imagesloaded.pkgd.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/isotope.pkgd.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/jquery.matchHeight-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/slick/slick/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/elevatezoom/jquery.elevatezoom.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/Magnific-Popup/dist/jquery.magnific-popup.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAx39JFH5nhxze1ZydH-Kl8xXM3OK4fvcg&amp;region=GB"></script><script type="text/javascript" src="{% static 'plugins/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <!-- Custom scripts-->
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>


    </body>
    </html>

shop/templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>
  .table>tbody>tr>td, .table>tfoot>tr>td{
    vertical-align: middle;
}
.margin-top{
  margin-top:-200px;
}
@media screen and (max-width: 600px) {
    table#cart tbody td .form-control{
		width:20%;
		display: inline !important;
	}
	.actions .btn{
		width:36%;
		margin:1.5em 0;
	}

	.actions .btn-info{
		float:left;
	}
	.actions .btn-danger{
		float:right;
	}

	table#cart thead { display: none; }
	table#cart tbody td { display: block; padding: .6rem; min-width:320px;}
	table#cart tbody tr td:first-child { background: #333; color: #fff; }
	table#cart tbody td:before {
		content: attr(data-th); font-weight: bold;
		display: inline-block; width: 8rem;
	}



	table#cart tfoot td{display:block; }
	table#cart tfoot td .btn{display:block;}
  .margin-top{
    margin-top: 0px;
    margin-bottom:10px;
    padding: 10px 10px;
    font-size:12px
  }
}
  </style>
<main class="ps-main">
<div class="container mt-4 pt-4">
  {% if order.OrderItem.all %}


	 <table id="cart" class="table table-hover table-condensed">
    			 	<thead>
					 	<tr>
					 		<th style="width:50%">Product</th>
					 		<th style="width:10%">Price</th>
					 		<th style="width:8%">Quantity</th>
					 		<th style="width:22%" class="text-center">Subtotal</th>
					 		<th style="width:10%"></th>
					 	</tr>
					</thead>
          {% for item in order.OrderItem.all %}
					<tbody>
						<tr>
							<td data-th="Product">
								<div class="row">
									<div class="col-sm-2 hidden-xs">

                    <img src="{{ item.product.productimages.first.image.url }}" alt="{{ item.product.ProductName }}" class="img-responsive"/>
                  </div>
									<div class="col-sm-10">
										<h4 class="nomargin">

                      {{ item.product.ProductName }}

                      </h4>
										<!-- <p>Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet.</p> -->
									</div>
								</div>
							</td>
							<td data-th="Price">
              <span><i>₹ {{ item.product.price }}</i></span>

              </td>
							<td data-th="Quantity">
								<input type="number" class="form-control text-center" value="{{item.quantity}}" disabled>
							</td>
							<td data-th="Subtotal" class="text-center">
              <span><i>₹ {{ item.get_prod_total }}</i></span>

              </td>
							<td class="actions" data-th="">
								<!-- <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button> -->
								<a href="{% url 'shop:deletefromcart' item.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>
							</td>
						</tr>
            {% endfor %}
					</tbody>
					<tfoot>
						<tr class="visible-xs">
							<td class="text-center"><strong>Total ₹{{ order.get_total }}</strong></td>
						</tr>
						<tr>
							<td><a href="#" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
							<td colspan="2" class="hidden-xs"></td>
							<td class="hidden-xs text-center"><strong></strong></td>
							<td><a href="{% url 'shop:checkout' %}" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
						</tr>
					</tfoot>
				</table>

        {% else %}
        <img src="{% static 'img/EmptyCart.jpg' %}" alt="">
    <center>    <a href="{% url 'home:index' %}" class="btn ps-btn margin-top">Back to shopping</a></center>
        {% endif %}
</div>
</main>
        {% endblock %}

shop/templates/checkoutload.html
{% load static %}


{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Account registration form</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, select, p {
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px;
      color: #666;
      }
      h1 {
      margin: 0;
      font-weight: 400;
      }
      h3 {
      margin: 12px 0;
      color: #8ebf42;
      }
      .main-block {
      display: flex;
      justify-content: center;
      align-items: center;
      background: #fff;
      }
      form {
      width: 100%;
      padding: 20px;
      }
      fieldset {
      border: none;
      border-top: 1px solid #8ebf42;
      }
      .account-details, .personal-details {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .account-details >div, .personal-details >div >div {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
      }
      .account-details >div, .personal-details >div, input, label {
      width: 100%;
      }
      label {
      padding: 0 5px;
      text-align: right;
      vertical-align: middle;
      }
      input {
      padding: 5px;
      vertical-align: middle;
      }
      .checkbox {
      margin-bottom: 10px;
      }
      select, .children, .gender, .bdate-block {
      width: calc(100% + 26px);
      padding: 5px 0;
      }
      select {
      background: transparent;
      }
      .gender input {
      width: auto;
      }
      .gender label {
      padding: 0 5px 0 0;
      }
      .bdate-block {
      display: flex;
      justify-content: space-between;
      }
      .birthdate select.day {
      width: 35px;
      }
      .birthdate select.mounth {
      width: calc(100% - 94px);
      }
      .birthdate input {
      width: 38px;
      vertical-align: unset;
      }
      .checkbox input, .children input {
      width: auto;
      margin: -2px 10px 0 0;
      }
      .checkbox a {
      color: #8ebf42;
      }
      .checkbox a:hover {
      color: #82b534;
      }
      button {
      width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px;
      border: none;
      background: #8ebf42;
      font-size: 14px;
      font-weight: 600;
      color: #fff;
      }
      button:hover {
      background: #F4CB79;
      }
      @media (min-width: 568px) {
      .account-details >div, .personal-details >div {
      width: 50%;
      }
      label {
      width: 40%;
      }
      input {
      width: 60%;
      }
      select, .children, .gender, .bdate-block {
      width: calc(60% + 16px);
      }
      }
    </style>
  </head>
  <body>
    <div class="main-block">




      <form action="{% url 'shop:check_response' %}" method="POST">{% csrf_token %}



       <fieldset>
         <legend>
           <h3>Personal Details</h3>
         </legend>
        <div class="personal-details">
           <div>
             <div><label>Name*</label><input type="text" name="name" placeholder="{{ name }}" disabled></div>
             <div><label>Phone*</label><input type="text" name="name" placeholder="{{ phone }}" disabled></div>
             <div><label>Email*</label><input type="text" name="name" placeholder="{{ email }}" disabled></div>
             <div><label>Address Line 1*</label><input type="text" name="name" placeholder="{{ invoice.Address1 }}" disabled></div>
             <div><label>Address Line 2</label><input type="text" name="name" placeholder="{{ invoice.Address2 }}" disabled></div>
             <div><label>City*</label><input type="text" name="name" placeholder="{{ invoice.city }}" disabled></div>
             <div><label>State*</label><input type="text" name="name" placeholder="{{ invoice.state }}" disabled></div>
            <div><label>Pincode</label><input type="text" name="name" placeholder="{{ invoice.zip_code }}" disabled></div>

           </div>

          </div>
       </fieldset>
         <script  src="https://checkout.razorpay.com/v1/checkout.js"
                    data-key="rzp_test_tUKqhcADEgW9fB"
                   data-amount="{{ price }}"
                   data-currency="INR"
                   data-order_id="{{ invoice_id }}"
                   data-buttontext="Pay with Razorpay"
                   data-name="Sayra Apparels Pvt Ltd"
                   data-description="Transaction"
                   data-image="{% static 'img/3.png' %}"
                   data-prefill.name="{{ name }}"
                   data-prefill.email="{{ email }}"
                   data-prefill.contact="{{ phone }}"
                   data-theme.color="#F4CB79"></script>
        <input type="hidden" custom="Hidden Element" name="hidden">




      </form>






    </div>
  </body>
  </html>